export const USER_INFO_QUERY = 'user-info'
export const USER_LIST_QUERY = 'users'
export const USER_SETTINGS_LIST_QUERY = 'user-settings'
export const USER_PROFILE_INFO_QUERY = 'profile-info'
export const USER_PROFILE_BASICS_QUERY = 'profile-basics'
