// Report routes
const REPORT_ROUTE = 'report-institutionalization'
export const REPORT_INSTITUTIONALIZATION_COUNTRY_ROUTE = `${REPORT_ROUTE}-country`
export const REPORT_INSTITUTIONALIZATION_COUNTRY_IN_DETAIL_ROUTE = `${REPORT_ROUTE}-country-detail`
export const REPORT_INSTITUTIONALIZATION_ORGANIZATION_ROUTE = `${REPORT_ROUTE}-organization`
export const REPORT_INSTITUTIONALIZATION_ASSESSMENT_ROUTE = `${REPORT_ROUTE}-assessment`
