export const INSTITUTIONALIZATION_ORGANIZATIONS_ASSESSMENTS_PRINT_ROUTE =
  'institutionalization-assessment-print/*'

export const INSTITUTIONALIZATION_PRINT_ROUTE_POSTFIX_REPORT = 'report'
export const INSTITUTIONALIZATION_PRINT_ROUTE_POSTFIX_GRAPH = 'graph'
